### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [hessnd/project10#1]
Looking mostly very good. Just a few issues I'd like you to try to fix:

- [These lines](https://github.com/hessnd/project10/blob/master/app/models/customer.rb#L2-L9) actually aren't necessary in the model (they just slow it down). They would be used in the controller (usually the `index` action) or in the Rails console to get a specific list from your database.
- There seems to be a styling issue that's putting any fields with validation errors out of alignment with the rest of the fields.
- I was able to enter a negative number for the quantity, which is probably undesired. [This resource](https://www.google.com/search?q=rails+validate+greater+than+0) may help you resolve that. (And I'm really not trying to be cheeky linking to a set of Google results - just trying to help you learn what to search for!)

Let me know how that goes and if you have any questions!

**Comment by hessnd** [comment]
Ha no I should of noticed that you could enter negative values into the field.  I fixed the styling of the errors and it now comes up with an error if you try and enter a value less than or equal to 0.

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
